- name: Install Apache2
  hosts: webservers
  become: yes
  tasks:

    - name: Ensure Apache service is started
      service:
        name: apache2  # Service name may vary based on Linux distribution
        state: started

