- name: Configurar firewall
  hosts: web
  tasks:

  - firewalld:
    service: https
    permanent: true
    state: enable
  
  - firewalld:
      port: 8081/tcp    
      permanent: true
      state: disable

  - firewalld:
      port: 161-162/udp    
      permanent: true
      state: disable

  - firewalld:
      source: 192.168.20.0/24   
      zone: internal
      state: enable